export const fixtures = {
  jurisdiction: "City of Example",
  building: "Fulton Yard 12",
  permit: "FP-2026-0571",
  program: "Fire alarm",
  citation: "NFPA 72",
  heroCitation: "NFPA 72, 14.4 annual",
  previousDue: "Aug 12, 2026",
  nextDue: "Aug 12, 2027",
  filed: "Filed 09:42",
  correctBy: "Sep 11",
  certificate: "CERT-2026-0812",
  contractor: "Northline Fire Protection",
  contractor2: "Calder Testing Co.",
  licence: "LIC-EX-1042",
  expired: "Licence expired",
  deficiencies: 2,
  rows: [
    {
      building: "Fulton Yard 12",
      program: "Fire alarm",
      last: "Aug 12, 2026",
      due: "Aug 12, 2027",
      status: "Pass",
    },
    {
      building: "Wren Works 04",
      program: "Fire sprinklers",
      last: "Sep 02, 2025",
      due: "Sep 02, 2026",
      status: "Due soon",
    },
    {
      building: "Morrow House 08",
      program: "Backflow prevention",
      last: "Aug 10, 2026",
      due: "Sep 11, 2026",
      status: "Deficiency",
    },
  ],
  route: [
    { time: "08:30", building: "Fulton Yard 12", task: "Fire alarm · Annual" },
    {
      time: "11:00",
      building: "Wren Works 04",
      task: "Fire sprinklers · Inspection",
    },
    {
      time: "14:00",
      building: "Morrow House 08",
      task: "Deficiency correction",
    },
  ],
} as const;
